### ISSUE TITLE
Wallabag API error code: 404

### ISSUE THREAD

**Issue by Wendigogo** [Joedmin/xExtension-wallabag-button#2]
Hi,

I got this 404 error issue when connecting to my Wallabag instance.

Is the API URL just the same as the website URL or is there something more to it. Like : https://wallabag.my/api ?

My Android application is working, but I can't check which address is used in client and it had been configured using QR code system...

**Comment by Wendigogo** [comment]
I found it!

I had to remove the tailing "/" in my Wallabag URL instance. Ie: from https://wallabag.my/ to https://wallabag.my

I let you close this bug if it's a normal behavior.

**Comment by Joedmin** [comment]
Ou, I thought it shouldn't matter. I'll add handling for it. Thank you for reporting it!

**Comment by Joedmin** [comment]
This one is fixed now. Released a new version 😁

**Comment by kvlkvlkvl** [comment]
I'm running into this error myself, but the trailing slash isn't the issue. Not certain what's happening. 

After I hit 'Connect to Wallabag' I get the error 'Access request failed! Wallabag API error code: 400' and both the password and secret are stripped. 

I have a dedicated client for this Extension, and I don't run into any issued with my Chrome Extension os iOS app. 

I looked around for a log file, but couldn't find one. 

If it makes any different, my Wallabag is a self hosted instance.

**Comment by Joedmin** [comment]
Hmm, how did you enter your url? With `https://`?

**Comment by kvlkvlkvl** [comment]
See image below. Same way I enter the credentials in the Wallabag iOS app (different id and secret, of coures). 

Is there a log file somewhere in the extention folder that I can look at? 

![Screenshot 2024-10-30 083121](https://github.com/user-attachments/assets/f17855fe-e6e1-408f-bb09-159742efcb9f)

**Comment by Wendigogo** [comment]
Is your server up? I receive a 404 error when I try to open https://read.kvl.me/web

Or maybe there is some protection rules allowing only some clients?

**Comment by kvlkvlkvl** [comment]
@Wendigogo Hmmm. That's weird. The server's up and running and I can access it from wherever. 

I'll poke around and see if there's something going on. the FreshRSS log file shows nothing on its own.

**Comment by Wendigogo** [comment]
It's up now! I can see the wallabag login page.

**Comment by Joedmin** [comment]
Now that I think of it, try setting it only to `https://read.kvl.me/` @Wendigogo

**Comment by Joedmin** [comment]
And also, did you set any `Redirect URIs` in wallabag? I left it empty and it's working for me. I'm just wondering, what's different between my instance config 🤔

**Comment by Joedmin** [comment]
I released a new version ([0.3](https://github.com/Joedmin/xExtension-wallabag-button/releases/tag/0.3)) to fix #6. Please try if it somehow fix the 404 error. I can't find a way to somehow replicate this issue but I would love to fix it with your help

**Comment by Wendigogo** [comment]
> Now that I think of it, try setting it only to `https://read.kvl.me/` @Wendigogo

Mine works perfectly (with another url). 😉

**Comment by Joedmin** [comment]
Do you have any idea why ut didn't work with the old domain?

**Comment by kvlkvlkvl** [comment]
> I released a new version ([0.3](https://github.com/Joedmin/xExtension-wallabag-button/releases/tag/0.3)) to fix #6. Please try if it somehow fixed the 404 error. I can't find a way to somehow replicate this issue but I would love to fix it with your help

The new version worked, along with the original url https://read.kvl.me/web

Both the old version, and the new, failed with the shortened url https://read.kvl.me/

Not sure of the reasoning or logic, but it's working now. 

Thanks for the help.

**Comment by Joedmin** [comment]
I guess the shortened version is just a bad endpoint in the end. I'm happy it works now for you! @kvlkvlkvl
