### ISSUE TITLE
Disabled Extension title "disappear" when Wallabag (|| Readeck) button is active

### ISSUE THREAD

**Issue by Wendigogo** [Joedmin/xExtension-wallabag-button#3]
I just find a weird bug by playing with both wallabag and readeck buttons extensions.

I think screenshots are the best option to illustrate the behavior:
![image](https://github.com/user-attachments/assets/56e8a2f9-fa44-4cd7-a606-d12d6f20a70a)
With none of Readeck nor Wallabag extension active.

![image](https://github.com/user-attachments/assets/25af1fb4-7a7a-40ab-ac8d-8c846b29af5b)
As you can see, when I activate the Readeck button extension disabled Extension title "disappear". The same occur with the Wallabag extension, so I guess it comes from the same shared code.

It's not a real big issue as I only have to activate a hidden extension to have his name appear again.

**Comment by Joedmin** [comment]
Hmm, I see. I've found this issue in other extensions as well. Will try to find a fix to it and notify other extensions.
![image](https://github.com/user-attachments/assets/0af95a13-0342-4885-988f-373233e41a80)
![image](https://github.com/user-attachments/assets/271674cc-f592-41cf-a852-69e7c5183d51)

Thank you for reporting it!

**Comment by Joedmin** [comment]
Released a new version 😁
