### ISSUE TITLE
 Access request failed! Wallabag API error code: 400 

### ISSUE THREAD

**Issue by guissmo** [Joedmin/xExtension-wallabag-button#6]
Hello, when I press "Connect to Wallabag" with my good credentials, I get **Access request failed**, as in the title.

I have FreshRSS and Wallabag installed on the same VPS, each with their own subdomain. I am using other apps to access the Wallabag API and they seem to work just fine.

I don't know where the logs are so I couldn't give more information.

Just in case it is relevant, this is my first time installing a FreshRSS plug-in (so perhaps I screwed that up). What I did was I entered the docker container in which FreshRSS lives, extracted the plugin (latest release) and then chown'd the extracted extension folder with `root:www-data` and gave `775` as permissions.

The plugin is detected by my FreshRSS instance but I am getting this cryptic 400 error.

Thanks for reading!

**Comment by deuts** [comment]
Me too. Wallabag and FreshRSS are installed in different servers though, and my wallabag instance is the full URL where I access it regularly. Also, when returning 400 error, the password and client secret fields are made blank with red borders.

**Comment by Joedmin** [comment]
I don't understand. I've selfhosted wallabag under my domain just to test it and it works. I believe this is the same issue as in #2  🤔

**Comment by Joedmin** [comment]
Are you setting the url to the base of your wallabag instance? For example not as `https://wallabag.joedmin.cz/unread/list` but as `https://wallabag.joedmin.cz/` @deuts @guissmo

**Comment by guissmo** [comment]
Yes. I am setting the URL at the base of the wallabag instance.

**Comment by Joedmin** [comment]
I see now where the issue is: it's the `&` character in the password. I'll add some handling to it, so it is send correctly in the request

**Comment by guissmo** [comment]
Oh cool! Thanks! For what it's worth, I have some non-`&` special characters in mine that might also need to be taken care of.

**Comment by Joedmin** [comment]
Thank you for letting me know! I will try to move the params from query to body, that would handle it. I'm now testing if Wallabag has this implemented.

**Comment by Joedmin** [comment]
I released a new version ([0.3](https://github.com/Joedmin/xExtension-wallabag-button/releases/tag/0.3)) with a fix to this issue. Thank you for reporting it to me.

You can update the extension by navigating to the extension folder and running `git pull` 😇 Please let me know if it helped (i did some testing and it did so I hope so 🙈)

**Comment by deuts** [comment]
Thanks it's working now!
